# Generated by Django 5.0.4 on 2024-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_gallery_content_alter_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='news_file',
            field=models.FileField(null=True, upload_to='website files'),
        ),
    ]
