# Generated by Django 5.0.4 on 2024-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_carousel_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('news_file', models.FileField(null=True, upload_to='e-journals')),
            ],
            options={
                'ordering': ('-uploaded',),
            },
        ),
    ]
