"""
Django settings for DjangoApp project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from decimal import Decimal
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o6_a-(vu9p6hwbd1^!ro)lvfk47hi*d38q+kr1nl0x+dy4_08('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'src',
    'website',
    'wallet',
    'admissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'src.middleware.ParentPortalOnlyMiddleware',
]

ROOT_URLCONF = 'DjangoApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'src.context_processors.data_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite serializes all writes at the database-file level. Without a
        # generous busy timeout, concurrent writers (e.g. wallet webhook
        # traffic) get an immediate "database is locked" error instead of
        # queueing behind the writer that currently holds the lock.
        'OPTIONS': {
            'timeout': 20,
        },
        # Use a real file for the test database instead of Django's default
        # in-memory shared-cache SQLite. The in-memory shared-cache mode has
        # different (stricter) table-locking semantics than a normal file-based
        # database, which produced "table is locked" errors under concurrent
        # writes in tests that the real db.sqlite3 file does not exhibit.
        'TEST': {
            'NAME': str(BASE_DIR / 'test_db.sqlite3'),
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# PAYSTACK_PUBLIC_KEY = "pk_test_f4a10df855357f8fb37f45a02b8f3ffd10457920"
# PAYSTACK_SECRET_KEY = "sk_test_48d51157ceb4150fb7f3b0cae2cd6840aa9c26d8"


PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")


ZAINPAY_SECRET_KEY = os.getenv("ZAINPAY_SECRET_KEY")
ZAINPAY_PUBLIC_KEY = os.getenv("ZAINPAY_PUBLIC_KEY")
ZAINPAY_BASE_URL = os.getenv("ZAINPAY_BASE_URL", "https://sandbox.zainpay.ng")

# Which provider actively funds/spends wallets right now - 'zainpay' or
# 'paystack'. Flipping this one setting is the whole switch: it controls both
# which checkout a parent is sent to when funding their wallet, and whether
# paying fees from the wallet does a real Zainpay Zainbox-to-Zainbox transfer
# (only correct when Zainpay is the active funding provider, since that's
# where the real money actually sits).
WALLET_FUNDING_PROVIDER = os.getenv("WALLET_FUNDING_PROVIDER", "zainpay")

# Zainbox 1: every parent's wallet top-up lands in this single pooled Zainbox
# (no per-parent virtual accounts anymore - Zainpay's checkout page collects
# from any channel and deposits straight into this account).
ZAINPAY_WALLET_ZAINBOX_CODE = os.getenv("ZAINPAY_WALLET_ZAINBOX_CODE", "76812_yJ8B7wyLV38ypP2Noqgc")
ZAINPAY_WALLET_ACCOUNT_NUMBER = os.getenv("ZAINPAY_WALLET_ACCOUNT_NUMBER", "4812833397")
ZAINPAY_WALLET_BANK_CODE = os.getenv("ZAINPAY_WALLET_BANK_CODE", "090976")

# Zainbox 2: the school's own Zainbox. Paying fees from a wallet transfers
# funds here from the wallet Zainbox above. Its own zainboxCode (distinct
# from the account/bank code above) is only needed when checking out
# directly into this box, e.g. the online admission application fee.
ZAINPAY_SCHOOL_SETTLEMENT_ACCOUNT_NUMBER = os.getenv("ZAINPAY_SCHOOL_SETTLEMENT_ACCOUNT_NUMBER", "4812350098")
ZAINPAY_SCHOOL_SETTLEMENT_BANK_CODE = os.getenv("ZAINPAY_SCHOOL_SETTLEMENT_BANK_CODE", "090976")
ZAINPAY_SCHOOL_ZAINBOX_CODE = os.getenv("ZAINPAY_SCHOOL_ZAINBOX_CODE", "89400_HSsbCKey2Luz8jaqhqOH")

# Online admission application fee, charged straight into the school Zainbox.
APPLICATION_FEE_AMOUNT = Decimal(os.getenv("APPLICATION_FEE_AMOUNT", "5000.00"))

SITE_BASE_URL = os.getenv("SITE_BASE_URL", "http://localhost:8000")

# Gmail SMTP, used for the admission-payment-confirmation email sent out by
# the sync_admission_payments cronjob. Credentials come from .env only - an
# app password, never the real account password.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Used only for the upfront "can this wallet afford this payment" UI check,
# before the real transfer happens. The actual debit always uses the real
# totalTxnAmount Zainpay returns, never this estimate.
ZAINPAY_TRANSFER_FEE_ESTIMATE = Decimal(os.getenv("ZAINPAY_TRANSFER_FEE_ESTIMATE", "300"))

# Without this, Python's default logging level (WARNING) silently drops every
# logger.info() call in the wallet app - including the webhook diagnostics -
# regardless of where stdout/stderr ends up. Writing to a dedicated file here
# means `tail -f wallet.log` always works, independent of how the app server
# is supervised (gunicorn/systemd/manual).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'wallet_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'wallet.log',
        },
    },
    'loggers': {
        'wallet': {
            'handlers': ['console', 'wallet_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

