# Generated by Django 6.0.5 on 2026-07-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src', '0039_guardian_address_guardian_occupation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('native_language', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], max_length=10)),
                ('has_ailment', models.BooleanField(default=False)),
                ('ailment_details', models.TextField(blank=True)),
                ('residential_address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applicants/photos/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_address', models.TextField(blank=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_qualification', models.CharField(blank=True, max_length=100)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_qualification', models.CharField(blank=True, max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('declaration_name', models.CharField(max_length=100)),
                ('declaration_agreed', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('interviewed', 'Interviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=100)),
                ('decided_by', models.CharField(blank=True, max_length=100)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desired_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants_desiring', to='src.schoolclass')),
                ('linked_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='src.student')),
                ('recommended_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_recommended', to='src.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='src.session')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Manual switch to close early, independent of capacity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_openings', to='src.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_openings', to='src.session')),
            ],
            options={
                'unique_together': {('session', 'school_class')},
            },
        ),
    ]
