# Generated by Django 6.0.5 on 2026-06-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_paymentmetadata'),
        ('wallet', '0003_virtualaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payments', models.ManyToManyField(related_name='wallet_payments', to='src.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.term')),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_payment', to='wallet.wallettransaction')),
            ],
        ),
    ]
