# Generated by Django 6.0.5 on 2026-06-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_walletpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentaccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='state',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='title',
        ),
    ]
