# Generated by Django 6.0.5 on 2026-07-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_walletfundingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredZainpayTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('narration', models.CharField(max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_transfer', to='wallet.walletpayment')),
            ],
        ),
    ]
