# Generated by Django 5.0.7 on 2024-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_student_enrolled_class_alter_student_guardians'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('notAdmitted', 'Not Admitted')], default='notAdmitted', max_length=20),
        ),
    ]
