# Generated by Django 5.0.7 on 2024-08-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_student_admission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
