# Generated by Django 5.0.7 on 2024-08-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('not_admitted', 'Not Admitted')], default='not_admitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, to='src.guardian'),
        ),
    ]
