# Generated by Django 5.0.7 on 2024-08-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_student_gender_alter_student_admission_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowYouFindUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
            ],
        ),
    ]
