# Generated by Django 5.0.7 on 2024-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_howyoufindus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='school_images/')),
                ('signature_image', models.ImageField(upload_to='school_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
