# Generated by Django 5.0.7 on 2024-08-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_schoolconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
