# Generated by Django 5.0.7 on 2024-09-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_result_ca1_marks_alter_result_ca2_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviouralAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('dedication', models.IntegerField(default=0)),
                ('participation', models.IntegerField(default=0)),
                ('hospitality', models.IntegerField(default=0)),
                ('neatness', models.IntegerField(default=0)),
                ('creativity', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
    ]
