# Generated by Django 5.1.3 on 2024-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('not_admitted', 'Not Admitted')], default='admitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
