# Generated by Django 5.1.3 on 2024-12-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_term_next_term_resupmtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(max_length=20, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_usage', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('associated_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.student')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.session')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.term')),
            ],
        ),
    ]
