# Generated by Django 5.1.3 on 2024-12-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahfeezResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(verbose_name='1st CA Marks')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
    ]
