# Generated by Django 5.1.3 on 2024-12-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_tahfeezresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahfeezresult',
            name='marks',
            field=models.IntegerField(verbose_name='Marks'),
        ),
    ]
