# Generated by Django 6.0 on 2025-12-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='src.paymentbatch'),
        ),
    ]
