# Generated by Django 6.0 on 2025-12-15 09:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_section_remove_feestructure_class_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 15, 9, 57, 35, 143240, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_type',
            field=models.CharField(choices=[('new', 'New Intake'), ('returning', 'Returning')], default='returning', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term_group',
            field=models.CharField(choices=[('first', 'First Term'), ('second_third', 'Second / Third Term')], default='first', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='transport',
            field=models.BooleanField(default=False, help_text='Includes transportation fee'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.section'),
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tuition, Feeding, Transport, Uniform', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='src.feestructure')),
            ],
        ),
    ]
