# Generated by Django 6.0 on 2025-12-19 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_rename_amount_feestructure_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('section', 'session', 'term_group', 'student_type', 'transport')},
        ),
        migrations.CreateModel(
            name='PartPaymentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254)),
                ('approved_amount', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed for part payment', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
    ]
