# Generated by Django 6.0 on 2025-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_payment_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
