# Generated by Django 6.0 on 2025-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_alter_payment_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='term_group',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=20),
        ),
    ]
