# Generated by Django 5.1.3 on 2025-12-30 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.section'),
        ),
    ]
