# Generated by Django 5.1.3 on 2025-12-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_alter_feestructure_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='paystack_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
