# Generated by Django 5.1.3 on 2026-01-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_otherfeestructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherFeeStructure',
        ),
    ]
