# Generated by Django 5.1.3 on 2026-04-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_payment_external_reference_payment_payment_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=20)),
                ('breakdown', models.JSONField()),
                ('parent_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='src.paymentbatch')),
            ],
        ),
    ]
