# Generated by Django 6.0.5 on 2026-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_paymentmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('waiver', 'Fee Waiver'), ('wallet', 'Wallet')], max_length=50),
        ),
    ]
