# Generated by Django 6.0.5 on 2026-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_guardian_address_guardian_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfeestructure',
            name='multi_child_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='When a parent pays this fee for more than one child in the same payment, every child after the first gets this percentage off. 0 means no discount.', max_digits=5),
        ),
    ]
