# Generated by Django 5.1.3 on 2026-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0040_otherfeestructure_multi_child_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='otherfeestructure',
            name='staff_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to every child (including the first) when the payer enters a valid active PromoCode. Overrides multi_child_discount_percent rather than stacking with it. 0 means no staff discount for this fee.', max_digits=5),
        ),
    ]
