# Generated by Django 5.1.3 on 2026-09-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0041_promocode_otherfeestructure_staff_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecomponent',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('learning_materials', 'Learning Materials'), ('feeding', 'Feeding'), ('uniform', 'Uniform'), ('ta_fees', 'TA Fees'), ('transportation', 'Transportation'), ('tahfeez', 'Tahfeez'), ('other', 'Other')], default='other', help_text='Item type used to filter/report payments, independent of the free-text name.', max_length=20),
        ),
        migrations.AddField(
            model_name='otherfeestructure',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('learning_materials', 'Learning Materials'), ('feeding', 'Feeding'), ('uniform', 'Uniform'), ('ta_fees', 'TA Fees'), ('transportation', 'Transportation'), ('tahfeez', 'Tahfeez'), ('other', 'Other')], default='other', help_text='Item type used to filter/report payments, independent of the free-text name.', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('learning_materials', 'Learning Materials'), ('feeding', 'Feeding'), ('uniform', 'Uniform'), ('ta_fees', 'TA Fees'), ('transportation', 'Transportation'), ('tahfeez', 'Tahfeez'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(help_text='Snapshot of the source component/other-fee name at payment time.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_estimated', models.BooleanField(default=False, help_text='True when amount is a computed proportional split of a bundled payment, not an exact per-item charge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_line_items', to='src.feecomponent')),
                ('other_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_line_items', to='src.otherfeestructure')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='src.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='src_payment_categor_695927_idx')],
            },
        ),
    ]
